#!/bin/bash
#set -x
config=/etc/port-forward.conf

function msg {
  std="${1}"
  shift
  case "${std}" in
    "err") [ -t 2 ] && echo $'\e[31m'"${@}"$'\e[0m' >&2 || echo "${@}" >&2;;
    "out") [ -t 1 ] && echo $'\e[32m'"${@}"$'\e[0m' || echo "${@}";;
  esac
}

function apply {
  if [ -z "${dest}" ] || [ -z "${dport}" ]; then
      echo "Rule '${comment}' malformed" >&2
    else
      [ -z "${sport}" ] && sport="${dport}"
      [ -z "${prot}" ] && prot="tcp udp" || prot="$(echo "${prot}" | sed 's/\s\+/\n/g;/^$/d' | sort -u)"
      [ -z "${src}" ] && src="0.0.0.0/0"
      sport="$(echo "${sport}" | sed 's/-/:/g')"
      dport="$(echo "${dport}" | sed 's/:/-/g')"
      for i in ${prot}; do
        iptables -t nat -A "${table}" \
                 -p "${prot}" -m multiport --dports "${sport}" \
                 -s "${src}" \
                 -j DNAT --to-destination "${dest}:${dport}" \
                 -m comment --comment "Port forward: ${comment}" 2>&1 || msg err "Rule '${comment}' malformed"
      done
  fi
}

function run {
  readarray rules < <(sed 's/^\s\+//;s/#.*$//;s/\s\+$//;/^$/d;s/\s/ /g' "$config")  || exit
  comment=""
  iptables -t nat --flush "${table}"
  for i in "${rules[@]}"; do
    line="${i::-1}"
    if [ "${line::1}${line:${#line} -1}" = "[]" ]; then
      [ -n "$comment" ] && apply
      comment="${line:1:-1}"
      src=""
      dest=""
      sport=""
      dport=""
      prot=""
    else
      value="$(echo "${line#*=}" | sed 's/^\s\+//;s/\s\+$//')"
      field="$(echo "${line%=*}" | sed 's/^\s\+//;s/\s\+$//')"
      case "${field}" in
        "src")   src="${value}" ;;
        "dest")  dest="${value}";;
        "sport") sport="${value}";;
        "dport") dport="${value}";;
        "prot")  prot="${value}";;
      esac
    fi
  done
  [ -n "$comment" ] && apply
  msg out "Port forwarding started"
}
(
  [ "$(id -u)" != "0" ] && {
    msg err "$(basename "${0}") must be run as root"
    exit 1
  }

  table="PFORWARD"
  [ "${1}" = "stop" ] && {
    iptables -t nat --flush "${table}"
    msg out "Port forwarding stopped"
  } || run
  exit 0
)
